### ISSUE TITLE
Installation frozen at esbuild step on 1.7.0-rc.1

### ISSUE THREAD

**Issue by timsu** [phoenixframework/phoenix#5207]
### Environment

* Elixir version (elixir -v): 1.14.2
* Erlang version: 24.3.3
* Phoenix version (mix deps): 1.7.0-rc.1
* Operating system: macOS 13.1

### Expected behavior

`mix phx.new` completes successfully

### Actual behavior

I ran `mix archive.install hex phx_new 1.7.0-rc.1` and then `mix phx.new myproject`

After generating all the files, it prints the following:

```
Fetch and install dependencies? [Yn]
* running mix deps.get
* running mix deps.compile esbuild tailwind
* running mix tailwind.install
* running mix esbuild.install
```

Then it hangs, I let it run for 30 minutes and it never finished.

After that, future runs of `mix phx.new` complete successfully and the `esbuild.install` step is instantaneous.

**Comment by JamesLavin** [comment]
I have the same problem with:
* Ubuntu 22.04.5
* elixir 1.14.2-otp-25
* erlang 25.2
* Phoenix 1.7.0-rc.1

I ran it all night last night, and it never completed. I've run it maybe five more times, including for several hours again.

**Comment by wceolin** [comment]
Make sure you have `esbuild` installed on your machine. I had this issue but it was fixed after I installed `esbuild` globally: `npm i esbuild -g`.

**Comment by JamesLavin** [comment]
This could well be a false lead, but I tried installing Phoenix `1.6.15` and eventually succeeded, but not until I downgraded `:castore`, which is a dependency of ESBuild. This is the error I hit:
```
james@...:~/Git/discovery$ mix ecto.create
Error while loading project :castore at /home/james/Git/discovery/deps/castore
** (File.Error) could not read file "VERSION": no such file or directory
    (elixir 1.14.2) lib/file.ex:358: File.read!/1
    /home/james/Git/discovery/deps/castore/mix.exs:50: CAStore.MixProject.version/0
    /home/james/Git/discovery/deps/castore/mix.exs:9: CAStore.MixProject.project/0
    (mix 1.14.2) lib/mix/project.ex:838: Mix.Project.get_project_config/1
    (mix 1.14.2) lib/mix/project.ex:141: Mix.Project.push/3
    (stdlib 4.2) lists.erl:1350: :lists.foldl/3
```
I decided to try downgrading `:castore` from `0.1.21` to `0.1.11` after seeing it was at `0.1.11` in this `mix.lock` file: https://github.com/phoenixframework/esbuild/blob/main/mix.lock:
```
%{
  "castore": {:hex, :castore, "0.1.11", "c0665858e0e1c3e8c...
```
Again, this may be irrelevant, but it could be a helpful clue because `:castore` is an `esbuild` dependency:
```
"esbuild": {:hex, :esbuild, "0.6.0", "9ba6ead054abd43cb...0f509c", [:mix], [{:castore, ">= 0.0.0"...
```

**Comment by wceolin** [comment]
I just ran into this issue too. I initially thought those issues were related but I'm not sure since `castore` is also a dependency from other packages too, including `phoenix` itself.

My guess is that we have two issues here:

- [esbuild.install](https://github.com/phoenixframework/esbuild) not installing `esbuild` itself.
- `castore`'s latest version not being supported yet.

But I'm new to Phoenix/Elixir, so I'm not sure, still trying to figure it out 😅

**Comment by wmealing** [comment]
I have come across the same problem, I followed wceolin's suggestion and installed npm and esbuild,  this did not solve the issue.  The system continues to stall at this time:

* running mix esbuild.install

$ mix local.rebar 

After having rebar3 installed, the "mix phx.new" command works correctly.

**Comment by wmealing** [comment]
My rebar3 missing must have been unrelated.

**Comment by chrismccord** [comment]
I don't think this is related to 1.7. I have gotten this a few times on 1.6 (and 1.7) with my home wifi. For some reason the download has been hanging or very slow to fetch the binary on my 2.4ghz channel, and changing to 5ghz always resolved it. The weird thing is my connections on 2.4ghz when this happened always seemed otherwise fine. I chalked it up to weird home wifi issues, but sounds like maybe our binary fetching internally in esbuild/tailwind/etc needs to at least report when the connection is hanging, which I believe is happening here. We can also work in retry logic in such cases.

**Comment by JamesLavin** [comment]
Thanks for all the responses. I didn't have time to try again till just now. Want to report that I wiped out the 1.6.15 archive (which did work, once I got past the apparent `castore` bug) and recreated the 1.7.0-rc.1 archive, then installed and started Phoenix without a hitch. No `castore` or `ESBuild` problem this time. I have no idea why `ESBuild` repeatedly hung previously but now works. The `castore` issue was a likely -- as @petermm noted -- the bug fixed by https://github.com/elixir-mint/castore/pull/52 because `mix.lock` now tells me I'm using `"castore": {:hex, :castore, "0.1.22"...`, which seems to fix the bug I hit.
